#!/usr/bin/env bash

# -- Reset environment variables -------------------------------------------

CPP_INCLUDE_PATH=
C_INCLUDE_PATH=
EDITOR=

# -- Set environment variables ---------------------------------------------

# Java
[[ -d /Library/Java/Home ]] && \
  JAVA_HOME=/Library/Java/Home

# TeX
[[ -d /usr/texbin ]] && \
  PATH=/usr/texbin:$PATH

# X11
[[ -d /usr/X11/bin ]] && \
  PATH=/usr/X11/bin:$PATH

# Groovy
if [[ -d /Library/Groovy/current ]]; then
  GROOVY_HOME=/Library/Groovy/current
  PATH=$GROOVY_HOME/bin:$PATH
fi

# Scala
if [[ -d /Library/Scala/current ]]; then
  SCALA_HOME=/Library/Scala/current
  PATH=$SCALA_HOME/bin:$PATH
fi

# Adobe Flex
[[ -d /Library/Flex/current/bin ]] && \
  PATH=/Library/Flex/current/bin:$PATH

# Adobe Air
[[ -d /Library/Air/current/bin ]] && \
  PATH=/Library/Air/current/bin:$PATH

# Node.js
if [[ -d /opt/node.js/current/bin ]]; then
  PATH=/opt/node.js/current/bin:$PATH
fi

# Textmate
if [[ -d /Applications/TextMate.app ]]; then
  EDITOR="mate -w"
else
  EDITOR="vim"
fi

# -- Export environment variables ------------------------------------------

export CPP_INCLUDE_PATH
export C_INCLUDE_PATH
export EDITOR

# -- Load RVM --------------------------------------------------------------

# RVM
[[ -s "/usr/local/rvm/scripts/rvm" ]] && \
  source "/usr/local/rvm/scripts/rvm"
