#!/usr/bin/env bash

# -- Path settings ---------------------------------------------------------

# Remove /usr/local/bin from PATH and position it BEFORE /usr/bin
__remove_path /usr/local/bin
__add_path /usr/local/bin

# Java
if [[ -d $(/usr/libexec/java_home) ]]; then
  export JAVA_HOME=$(/usr/libexec/java_home)
  __add_path $JAVA_HOME/bin
fi

# TeX
[[ -d /usr/texbin ]] && \
  __add_path /usr/texbin

# X11
[[ -d /usr/X11/bin ]] && \
  __add_path /usr/X11/bin

# Groovy
if [[ -d /Library/Groovy/current ]]; then
  export GROOVY_HOME=/Library/Groovy/current
  __add_path $GROOVY_HOME/bin
fi

# Scala
if [[ -d /Library/Scala/current ]]; then
  export SCALA_HOME=/Library/Scala/current
  __add_path $SCALA_HOME/bin
fi

# Node.js
[[ -d /usr/local/lib/node_modules ]] && \
  export NODE_PATH=/usr/local/lib/node_modules

# Python (when installed via homebrew)
[[ -d /usr/local/share/python ]] && \
  __add_path /usr/local/share/python

# -- Editor settings -------------------------------------------------------

if [[ -d /Applications/Chocolat.app ]]; then
  EDITOR="choc"
elif [[ -d /Applications/TextMate.app ]]; then
  EDITOR="mate -w"
else
  EDITOR="vim"
fi; export EDITOR
