alias g git
alias ga "git add"
alias gc "git commit"
alias gca "git commit --amend"
alias gca! "git commit --amend --no-edit"
alias gco "git checkout"
alias gd "git diff"
alias gis "gh issue"
alias gl "git log"
alias glo "git log --oneline"
alias gp "git push"
alias gpr "gh pr"
alias gprc "gh pr create"
alias gprv "gh pr view --web"
alias gpt "git push --set-upstream"
alias gpt "git push origin -u (git current-branch)"
alias gptf "git push origin --force-with-lease -u (git current-branch)"
alias grb "git rebase"
alias grb "git rebase"
alias grba "git rebase --abort"
alias grbc "git rebase --continue"
alias grbi "git rebase --interactive"
alias gs "git status"
alias gt "git tree"
