#!/usr/bin/env zsh

if [ `uname` = "Linux" ]; then
  pushd `mktemp -d`
  wget https://github.com/dandavison/delta/releases/download/0.6.0/git-delta_0.6.0_amd64.deb
  sudo dpkg -i git-delta_0.6.0_amd64.deb
  popd
fi

yes | rake install
