#!/usr/bin/env bash

webinstall() {
  local installation_dir="$1"
  local home_dir=`( cd; pwd -P )`

  # Fail if git is not installed
  if ! which git > /dev/null; then
    echo "git is not installed" 1>&2
    return 1
  fi

  # Fail if no repository directory was specified
  if [[ -z $installation_dir ]]; then
    echo "Installation directory not specified" 1>&2
    return 1
  fi

  # Fail if the installation directory does already exist
  if [[ -e "$installation_dir" ]]; then
    echo "Installation directory does already exists: $installation_dir" 1>&2
    return 1
  fi

  # Clone repository
  if mkdir -p `dirname "$installation_dir"`; then
    git clone --quiet https://github.com/t6d/dotfiles.git "$installation_dir"
  else
    echo "Could not create installation directory" 1>&2
    exit 1
  fi

  # Load dotfiles and perform actual installation
  (
    cd "$installation_dir"
    source .bashrc
    dotfiles update
    dotfiles link
  )
}

webinstall "$@"

