#!/usr/bin/env bash

##
# Allows to edit, reload and update the dotfiles
#
# Params: cd|edit|reload|update
dotfiles() {
  local directory=$(dirname $(readlink -f ~/.bashrc))

  case $1 in
    cd)
      cd $directory
    ;;

    edit)
      $EDITOR $directory
    ;;

    reload)
      source ~/.bashrc
    ;;

    update)
      ( cd $directory; rake update )
      dotfiles reload
    ;;

    *)
      echo "Usage: dotfiles cd|edit|reload|update"
    ;;
  esac
}

##
# Bash completion for dotfiles function
_dotfiles() {
  if [[ $COMP_CWORD == 1 ]]; then
    COMPREPLY=( $(compgen -W "cd edit reload update" -- ${COMP_WORDS[COMP_CWORD]}) )
  fi
}
complete -F _dotfiles dotfiles