#!/usr/bin/env bash

##
# Allows to edit, reload and update the dotfiles
#
# Params: cd|edit|reload|update
dotfiles() {
  local local_dotfiles
  local global_dotfiles
  
  if readlink ~/.localrc > /dev/null; then
    local_dotfiles=$(dirname $(readlink ~/.localrc))
  fi
  
  global_dotfiles=$(dirname $(readlink ~/.bashrc))

  case $1 in
    cd)
      cd $global_dotfiles
    ;;

    edit)
      echo $EDITOR $global_dotfiles $local_dotfiles
      $EDITOR $global_dotfiles $local_dotfiles
    ;;

    reload)
      source ~/.bash_profile
    ;;

    update)
      ( cd $global_dotfiles; rake update )
      dotfiles reload
    ;;

    *)
      echo "Usage: dotfiles cd|edit|reload|update"
    ;;
  esac
}

##
# Bash completion for dotfiles function
_dotfiles() {
  local cur cword
  _get_comp_words_by_ref cur cword
  
  [[ $cword > 1 ]] && return 0
  
  COMPREPLY=( $(compgen -W "cd edit reload update" -- $cur) )
}
complete -F _dotfiles dotfiles