#!/usr/bin/env bash

##
# Allows to edit, reload and update the dotfiles
#
# Params: cd|edit|reload|update
dotfiles() {
  
  __FILE__() {
    expand_path ${BASH_SOURCE[0]}
  }
  
  __DIR__() {
    dirname $(__FILE__)
  }
  
  case $1 in
    cd)
      cd $(dotfiles path)
    ;;

    edit)
      echo $EDITOR $(dotfiles path)
      $EDITOR $(dotfiles path)
    ;;

    reload)
      source ~/.bash_profile
    ;;

    update)
      ( cd $global_dotfiles; rake update )
      dotfiles reload
    ;;
    
    path)
      expand_path $(__DIR__)/../..
    ;;

    *)
      echo "Usage: dotfiles cd|edit|path|reload|update"
    ;;
  esac
  
  unset __FILE__
  unset __DIR__
}

##
# Bash completion for dotfiles function
_dotfiles() {
  local cur cword
  _get_comp_words_by_ref cur cword
  
  [[ $cword > 1 ]] && return 0
  
  COMPREPLY=( $(compgen -W "cd edit path reload update" -- $cur) )
}
complete -F _dotfiles dotfiles