#!/usr/bin/env bash

##
# Returns the full qualified path for a file or directory. The function also
# resolves symbolic links.
#
expand_path() {
  _readlink() {
    local path=$1

    while [[ -h $path ]]; do
      path=$(readlink "$path")
    done

    echo $path
    return 0
  }
  
  if [[ $# -eq 0 ]]; then
    echo $(builtin cd -P "$(pwd)" && pwd)
  else
    local path=$(_readlink "$1"); shift
    
    if [[ -d $path ]]; then
      echo $(builtin cd -P "$path" && pwd)
    elif [[ -e $path ]]; then
      echo $(builtin cd -P "$(dirname "$path")" && pwd)/$(basename "$path")
    fi
  fi
  
  unset _readlink
}