#!/usr/bin/env bash

expand_path() {
  _readlink() {
    local path=$1; shift

    while [[ -h $path ]]; do
      path=$(readlink $path)
    done

    echo $path
    return 0
  }
  
  local path=$(_readlink $1); shift
  if [[ -d $path ]]; then
    echo $(cd -P "$path" && pwd)
  else
    echo $(cd -P "$(dirname "$path")" && pwd)/$(basename "$path")
  fi
  
  unset _readlink
}