#!/usr/bin/env bash

##
# Returns the relative path to a given base path.
# Params: <source> <target>
#
relative_path() {
  IFS="/" read -a source <<< "${1%/}"
  IFS="/" read -a target <<< "${2%/}"

  local path=""
  local common=0
  for element in "${source[@]}"; do
    if [[ $element == ${target[$common]} ]]; then
      common=$((common + 1))
    fi
  done

  if [[ $common -gt 1 ]]; then
    for element in ${source[@]:$common}; do
      path="../$path"
    done

    path=${path%/}

    for element in ${target[@]:$common}; do
      if [[ -z $path ]]; then
        path=$element
      else
        path="$path/$element"
      fi
    done

    echo $path
  else
    for element in ${target[@]}; do
      path="$path/$element"
    done
    echo $path
  fi
}

