#!/usr/bin/env bash

restore() {
  local target=$1; shift
  target=${target%/}
  
  local working_directory=$(pwd)
  
  local relative_path=${working_directory##$HOME}
  relative_path=${relative_path#/}
  relative_path=${relative_path%/}
  
  local prefix=/Volumes/Backup
  #local prefix=/Volumes/harpertown/Backups.backupdb/harpertown/Latest/Data/Users/h4rper
  
  if [[ -n $relative_path ]]; then
    local source="$prefix/$relative_path/$target"
  else
    local source="$prefix/$target"
  fi
  
  if [[ -f $source || -d $source ]]; then
    echo rsync -av --no-owner --no-group --chmod=a-x,go-w,Da+x "$source" .
    rsync -av --no-owner --no-group --chmod=a-x,go-w,Da+x "$source" .
  else
    echo "File or directory not found - $source"
  fi
}