#!/usr/bin/env bash

##
# Allows to edit, reload and update the dotfiles
#
# Params: cd|edit|reload|update
smart-install() {
  case $1 in
    homebrew)
      ruby <(curl -fsSk https://raw.github.com/mxcl/homebrew/go)
    ;;

    pow)
      curl get.pow.cx | sh
    ;;

    rvm)
      bash < <(curl -s https://rvm.beginrescueend.com/install/rvm)
    ;;

    rbenv)
      git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
    ;;

    ruby-build)
      git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
    ;;

    *)
      echo "Usage: smart-install homebrew|pow|rbenv|ruby-build|rvm"
    ;;
  esac
}

##
# Bash completion for dotfiles function
_smart-install() {
  local cur cword
  _get_comp_words_by_ref cur cword

  [[ $cword > 1 ]] && return 0

  COMPREPLY=( $(compgen -W "homebrew pow rbenv ruby-build rvm" -- $cur) )
}
complete -F _smart-install smart-install
