#!/usr/bin/env bash

##
# Allows one to generate ssh key pairs and copy them to remote hosts.
sshkey() {
  __sshkey_usage() {
    echo "Usage: sshkey generate|copy [remote-host]"
  }
  
  local command=$1; shift
  
  case $command in
    generate)
      ssh-keygen $@
    ;;
    copy)
      cat ~/.ssh/id_rsa.pub | \
      ssh $1 "[[ ! -d ~/.ssh ]] && mkdir ~/.ssh; cat >> ~/.ssh/authorized_keys2"
    ;;
    *)
      __sshkey_usage
      return 1
    ;;
  esac
  
  unset __sshkey_usage
  return 0
}

##
# Bash completion for sshkey function
_sshkey() {
  local cur cword
  _get_comp_words_by_ref cur cword
  
  [[ $cword > 1 ]] && return 0
  
  COMPREPLY=( $(compgen -W "generate copy" -- $cur) )
}
complete -F _sshkey sshkey
