#!/usr/bin/env bash

##
# Checks if the user is the root user.
#
# Returns: 0 if the user is the root user,
#          1 otherwise.
user_is_root() {
  if [[ `whoami` == 'root' ]]; then
    return 0
  else
    return 1
  fi
}