#!/usr/bin/env bash

##
# Checks if the user is logged in from another machine.
#
# Returns: 0 if the user is logged in from another machine,
#          1 otherwise.
user_is_logged_in_remotely() {
  if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
    return 0
  else
    case $(ps -o comm= -p $PPID) in
      sshd|*/sshd) return 0;;
    esac
  fi

  return 1
}
