#!/bin/zsh

# -- Path settings ---------------------------------------------------------

# TeX
[[ -d /usr/texbin ]] && \
  __shift_path /usr/texbin

# X11
[[ -d /usr/X11/bin ]] && \
  __shift_path /usr/X11/bin

__shift_path /usr/local/bin

# Java
if /usr/libexec/java_home > /dev/null 2>&1; then
  export JAVA_HOME=$(/usr/libexec/java_home)
  __shift_path $JAVA_HOME/bin
fi

# Groovy
if [[ -d /Library/Groovy/current ]]; then
  export GROOVY_HOME=/Library/Groovy/current
  __shift_path $GROOVY_HOME/bin
fi

# Scala
if [[ -d /Library/Scala/current ]]; then
  export SCALA_HOME=/Library/Scala/current
  __shift_path $SCALA_HOME/bin
fi

# Node.js
if [[ -d /usr/local/share/npm ]]; then
  export NODE_PATH=/usr/local/share/npm/lib/node_modules
  __shift_path /usr/local/share/npm/bin
fi

# Postgres.app
[[ -d /Applications/Postgres.app ]] && \
  __shift_path /Applications/Postgres.app/Contents/MacOS/bin

# Python 2.7
[[ -d /Users/t6d/Library/Python/2.7/bin ]] && \
  __shift_path /Users/t6d/Library/Python/2.7/bin

# Homebrew
if [[ -d /opt/homebrew ]]; then
  __shift_path /opt/homebrew/bin
  eval $(/opt/homebrew/bin/brew shellenv)
fi

# -- Nix -------------------------------------------------------------------

if [ -e /Users/t6d/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/t6d/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

