#!/bin/zsh

# -- Path settings ---------------------------------------------------------

# Cuda
if [[ -d /usr/local/cuda ]]; then
  export PATH=/usr/local/cuda/bin:$PATH
  export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
fi

# -- Misc ------------------------------------------------------------------

export EDITOR='vim'