#!/usr/bin/env zsh

# --------------------------------------------------------------------------
# cd
# --------------------------------------------------------------------------

alias ..="cd .."
alias ...="cd ../.."

# --------------------------------------------------------------------------
# git, svn, etc.
# --------------------------------------------------------------------------

alias g="git"
alias ga="git add"
alias gai="git add -i"
alias gcav="git commit -v -a"
alias gcv="git commit -v"
alias gc="git commit"
alias gco="git checkout"
alias gcob="git checkout -b $1"
alias gd="git diff --color"
alias gp="git push"
alias gl="git pull"
alias gs="git status"

alias gitx="open -a GitX"

# --------------------------------------------------------------------------
# ls
# --------------------------------------------------------------------------

alias ls="ls --color=auto"
alias ll='ls -hl'
alias la='ls -Ah'
alias lla='ls -Ahl'

