#!/usr/bin/env zsh

# --------------------------------------------------------------------------
# cd
# --------------------------------------------------------------------------

alias ..="cd .."
alias ...="cd ../.."
alias cd!="cd ..; cd -"

# --------------------------------------------------------------------------
# git, svn, etc.
# --------------------------------------------------------------------------

alias g="git"
alias ga="git add"
alias gc="git commit"
alias gco="git checkout"
alias gd="git diff"
alias gs="git status"

# Auto Completion
__git_complete g _git
__git_complete ga _git_add
__git_complete gc _git_commit
__git_complete gco _git_checkout
__git_complete gd _git_diff
__git_complete gs _git_status

# --------------------------------------------------------------------------
# ls
# --------------------------------------------------------------------------

alias ls="ls --color=auto"
alias ll='ls -hl'
alias la='ls -Ah'
alias lla='ls -Ahl'
