#!/usr/bin/env bash

# --------------------------------------------------------------------------
# Prompt configuration
# --------------------------------------------------------------------------

function __configure_prompt() {

  # Colors
  local black="\[\e[1;30m\]"    # black
  local red="\[\e[1;31m\]"      # red
  local green="\[\e[1;32m\]"    # green
  local yellow="\[\e[1;33m\]"   # yellow
  local blue="\[\e[1;34m\]"     # blue
  local magenta="\[\e[1;35m\]"  # magenta
  local cyan="\[\e[1;36m\]"     # cyan
  local white="\[\e[1;37m\]"    # white

  # Text variants
  local bold="\[\e[1m\]"
  local underlined="\[\e[4m\]"

  # Reset color
  local reset="\[\e[0m\]"

  local username
  local host
  local directory
  local status
  local ruby_version

  if user_is_root; then
    username="$red$underlined\u$reset"
  else
    username="$magenta\u$reset"
  fi

  if user_is_logged_in_remotely; then
    host="$underlined$yellow\h$reset"
  else
    host="$green\h$reset"
  fi

  directory="$cyan\w$reset"

  if which vcprompt > /dev/null; then
    status="$black\$(vcprompt)$reset"
  else
    status=""
  fi

  if  which rbenv > /dev/null; then
    ruby_version="$black[ruby:\$(rbenv version-name)]$reset"
  else
    ruby_version=""
  fi

  PS1="\n$username$bold@$reset$host$bold:$reset$directory $ruby_version $status\n$ "
}

__configure_prompt; unset __configure_prompt

# --------------------------------------------------------------------------
# Bash completion
# --------------------------------------------------------------------------

# Linux/Unix default
[[ -f /etc/bash_completion ]] && source /etc/bash_completion

# Homebrew for Version 1
[[ -x `which brew` && -f `brew --prefix`/etc/bash_completion ]] && \
  source `brew --prefix`/etc/bash_completion

# Homebrew for Version 2
[[ -x `which brew` && -f `brew --prefix`/share/bash_completion/bash_completion ]] && \
  source `brew --prefix`/share/bash_completion/bash_completion

