#!/usr/bin/env bash

function __config() {

  # ------------------------------------------------------------------------
  # Color definitions
  # ------------------------------------------------------------------------

  # Colors
  local black="\[\e[1;30m\]"    # black
  local red="\[\e[1;31m\]"      # red
  local green="\[\e[1;32m\]"    # green
  local yellow="\[\e[1;33m\]"   # yellow
  local blue="\[\e[1;34m\]"     # blue
  local magenta="\[\e[1;35m\]"  # magenta
  local cyan="\[\e[1;36m\]"     # cyan
  local white="\[\e[1;37m\]"    # white

  # Text variants
  local bold="\[\e[1m\]"
  local underlined="\[\e[4m\]"

  # Reset color
  local reset="\[\e[0m\]"

  # ------------------------------------------------------------------------
  # Prompt configuration
  # ------------------------------------------------------------------------

  local username
  local host
  local directory
  local status
  
  if [[ $USER == "root" ]]; then
    username="$red$underlined\u$reset"
  else
    username="$magenta\u$reset"
  fi

  if ${REMOTE_LOGIN:=false}; then
    host="$underlined$yellow\h$reset"
  else
    host="$green\h$reset"
  fi

  directory="$cyan\w$reset"

  if which vcprompt > /dev/null; then
    status="$black\$(vcprompt)$reset"
  else
    status=""
  fi

  PS1="\n$username$bold@$reset$host$bold:$reset$directory $status\n$ "

  # ------------------------------------------------------------------------
  # Bash completion
  # ------------------------------------------------------------------------

  [[ -f /opt/local/etc/bash_completion ]] && \
    source /opt/local/etc/bash_completion
}

__config; unset __config