#!/usr/bin/env bash

##
# Checks if the user is the root user.
#
# Returns: 0 if the user is the root user,
#          1 otherwise.
function user_is_root() {
  if [[ `whoami` == 'root' ]]; then
    return 0
  else
    return 1
  fi
}

##
# Checks if the user is logged in from another machine.
#
# Returns: 0 if the user is logged in from another machine,
#          1 otherwise.
function user_is_logged_in_remotely() {
  local remote_host=`who am i | awk -F '[()]' '{print $2}'`
  
  if [[ -z $remote_host ]] || [[ $remote_host == 'localhost' ]]; then
    return 1
  else
    return 0
  fi
}